### ISSUE TITLE
Broken Instagram Link

### ISSUE THREAD

**Issue by aydenjahola** [cs-soc-tudublin/Plume#11]
Latest push seemed to break the Instagram link located in `src/_data/site.yml` line 41

**Comment by CostDeath** [comment]
wdym? It's the new social media linkedinstagram!

Meta is trying to make a job hunting site look [here](https://www.youtube.com/watch?v=UIp6_0kct_U)

**Comment by RJMurg** [comment]
Resolved.
Cheers!
