### ISSUE TITLE
Open Graph Embed/Preview Lacks Image

### ISSUE THREAD

**Issue by ArcaneIRE** [cs-soc-tudublin/Plume#20]
I think it'd be nice if the preview had an image. [This commit](https://github.com/cs-soc-tudublin/Plume/commit/7686e78e5ae081376052d5fea3471d854a9e57bf) on the upstream seems to add them 

Current:
![image](https://github.com/user-attachments/assets/2865e3e5-e0c4-4262-bbc6-2da9dcdd3f37)

**Comment by RJMurg** [comment]
Not resolved.

**Comment by ArcaneIRE** [comment]
Odd. This validator is showing the previews correctly. I thought it might be due to discord caching the old preview but I've tested on twitter and using URL variations (https://cspp.ie/#), neither of which have shown the image.  
https://www.opengraph.xyz/url/https%3A%2F%2Fcspp.ie
![image](https://github.com/user-attachments/assets/150966da-f7b9-44f4-8e1f-fe2cc2747ffe)

**Comment by ArcaneIRE** [comment]
Ah, the image is using a github URL. It doesnt load when I open the link in my browser

![image](https://github.com/user-attachments/assets/de5f28e5-f744-4d9c-956c-41f08a4ef98b)

**Comment by RJMurg** [comment]
We don't keep the roundel in Plume at all!

RB did a funny where they used AWS for a CDN. We could follow in those steps. Or just host the image in plume.

**Comment by ArcaneIRE** [comment]
Hosting it in Plume seems like the natural option to me. We already have our other images in there, right? E.g. committee portraits

**Comment by RJMurg** [comment]
I think we should actually pay 8 million for cloud hosting costs!

The reason Plume doesn't hold a copy of the roundel is because of IdentityFlip which hosts the "master" logo, fonts and themeing. 

Let me do some digging.

**Comment by RJMurg** [comment]
RB's works because they use a PNG of their logo. I'll add that to IdentityFlip and add a link to that in the site YAML
