### ISSUE TITLE
Social Media Priority on Homepage

### ISSUE THREAD

**Issue by ArcaneIRE** [cs-soc-tudublin/Plume#7]
Would it be possible to add our instagram link somewhere up at the top of the page?

It's the biggest social media platform and one of the main ways we reach people, as well as being the main stream of activity for past and current events.

I think ideally for me, the discord button would be replaced with two smaller discord and instagram buttons that only show icons

![image](https://github.com/user-attachments/assets/019ed4a5-7217-42c7-b959-63fe20766fe3)

**Comment by RJMurg** [comment]
Discord button on hero replaced w/ Instagram and Discord buttons.
Header button remains same. Maybe replace with LinkTree?
